### ISSUE TITLE
custom repos default

### ISSUE THREAD

**Issue by charlesbodhi** [stacefauske/bodhibuilder_2.18.x_all#6]
We got a request from Jeff to have the (trusted) bodhi repository by default in the custom repos file so he can't forget to write it out half of the time.
Should be like this:
# - - - Bodhi 5.x repository - - - # 
deb [trusted=yes] http://packages.bodhilinux.com/bodhi bionic b5main

Can you prevent that it appears twice once the system is installed?

**Comment by stacefauske** [comment]
Added repo to file.
Testing installed system for duplicate entries.

**Comment by stacefauske** [comment]
Got this working.
Leaving this open though because I'm going to remove custom_repos completely starting in ver 2.18.4_all and whatever is in /etc/apt/sources.list at the time of ISO creation is what will be put into the installed system.
Inwork.

**Comment by stacefauske** [comment]
Removed custom_repos file from BB in 2.18.4. Now, whatever is in /etc/apt/sources.list is what will be brought to the installed system. The live ISO will have the same file, but with an additional cdrom repo as well to allow for some minimum offline package access.
Closing.
