### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by linuxlite** [stacefauske/bodhibuilder_2.18.x_all#7]
Thank you for your work on this. We're able to now offer a UEFI ISO thanks to your work. Where can I send a donation for this?

**Comment by stacefauske** [comment]
It is our pleasure.
If you feel like you have to donate (this might seem a bit weird), please donate to [bodhi linux](https://www.bodhilinux.com/donate/). It's not just me working and testing this script, they're in it up to their elbows too with Moksha, Bodhi, Bodhibuilder, etc.
On behalf of the Bodhi team, thanks for the kudos, it's good to hear. Linux is an awesome community!!!
